version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smartseason_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - certbot_webroot:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_webroot:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  postgres_data:
  static_volume:
  certbot_webroot: